### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by idkjs** [maxogden/toiletdb#5]
Just an FYI. Was playing with this. Got this error when trying to run:

 ```
/Users/klik/Desktop/toiletdb-test/node_modules/toiletdb/index.js:39
        cb(null, state)
        ^

TypeError: cb is not a function
    at /Users/klik/Desktop/toiletdb-test/node_modules/toiletdb/index.js:39:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

**Comment by TehShrike** [comment]
Can you paste the code that caused the error to happen?

**Comment by idkjs** [comment]
Sorry, brother. Deleted it. I will try to mess around with it again and reproduce it for you.
